### ISSUE TITLE
Support MP Connect

### ISSUE THREAD

**Issue by arielfr** [mercadopago/dx-nodejs#111]
The SDK needs to support MP Connect.

**Comment by arielfr** [comment]
@paulogdm Let you know when this is done

**Comment by paulogdm** [comment]
That was fast. Ty!

**Comment by arielfr** [comment]
@paulogdm Just bumped to version `1.0.19`. To use it you just need to pass as configuration the access token of the user you want to impersonate. Example:

```javascript
mercadopago.${type}.${operation}(${payload}, {
  access_token: 'XXXXXX',
})
```

Thank you again!

**Comment by paulogdm** [comment]
@arielfr I need to say: Thank you for making this little adjustment, it worked like a charm!
---
When the documentation of MP Developers does not reflect the real implementation of the SDK (and the wiki), it turns developing into a real time consuming guessing game. I lost at least 40 hours trying to figure out if I should follow the the wiki or the flow of the docs. I have been pressing my Scrum Master and PO for a change in the payment solution requisites while struggling to figure out the docs (not anymore). I'm 100% sure MercadoPago is losing business because of the poor documentation and the lack of good examples.
I believe that MercadoPago has the manpower to do a better documentation and also respect his developers as customers. What I don't understand is why it is in such a bad shape, like we have objects like this:
```
var payment_data = {
  transaction_amount: 100,
  token: 'ff8080814c11e237014c1ff593b57b4d'
  description: 'Title of what you are paying for',
  installments: 1,
  payment_method_id: 'visa',
  user_token: "ENV_USER_TOKEN"
  payer: {
    email: 'test_user_3931694@testuser.com'
  }
};
```
that don't even have `,` between the key and values. It raises questions like "was this really tested"?

A few examples to inspire:
 * https://zeit.co/docs
 * https://www.gatsbyjs.org/docs/
 * https://docs.scaleapi.com/
 * https://developers.coinbase.com/api/v2

Guys, please, take this as an advice to improve and you will see your business grow in the process.

**Comment by arielfr** [comment]
@paulogdm Thank you for your feedback and support!. You are right on every point and I will do my best to contact everyone involve to enrich our documentation. On MercadoPago we are currently working on increase our Developer Experience team to achieve those goals.

Thank you again for your feedback!

Cheers!
