### ISSUE TITLE
Send items from JavaScript to Node.JS

### ISSUE THREAD

**Issue by mQserv** [mercadopago/dx-nodejs#76]
Hello folks,
I've been struggling with the custom-checkout, and this px-nodejs SDK.

See, I have a shopping cart (all made by myself).
And a button "Comprar".

In the button, it shows a modal with the form of MercadoPago to submit the card's data;
but how can I make the payment?

Through AJAX?

I checked out all the examples and none of them answers my question.
And the documentation here seems pretty.. it lacks of it.

This is the repo for the form (JavaScript):
https://github.com/matikbird/mercadopago-payment-form

Now, where and how do I place the payment?

Please, provide complete examples. It would help us all.

Thanks in advance.

**Comment by matikbird** [comment]
─And yes, I check out this URL: [https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/charge-with-creditcard/javascript/](https://www.mercadopago.com.ar/developers/es/solutions/payments/custom-checkout/charge-with-creditcard/javascript/)

But that is for the other repo. I want to use this, since it includes one of my libraries: Bluebird.

Based on your answers, I'll update the repo with the SDK (px-nodejs and not the old node.js).

Again, thanks.

**Comment by arielfr** [comment]
Hi @mQserv 

As far as i read the repository. The [script](https://github.com/mQserv/mercadopago-payment-form/blob/master/js/mp-handler.js) implements the Javascript SDK. This library only gives you the identification types ann **tokenize** the credit_card data. Consider this as a helper to make your checkout page. Then, when you execute the method `sdkResponseHandler ` on the token generator (on the submit event), you need to send to your server the TOKEN, and the data that you want to send (PCI Compliance, don't send the credit card number!). An finally you need to do the payment on the server using the card token. If you do it with NodeJS, you can use this library.

Cheers,
