### ISSUE TITLE
MercadoPago Connect y vambiar configuracion en the fly para poder cobrar a nombre del cliente

### ISSUE THREAD

**Issue by yairvillarp** [mercadopago/dx-nodejs#98]
en este momento en el proceso de compra yo cambio la configuracion 
```
mercadopago.configure({
     sandbox: config.mp.sandbox,
     access_token: prod.store_id.mp.access_token
 });
```

y despues genero el pago

```
var payload = {
                        "transaction_amount": total,
                        "token": req.body.token,
                        "description": prod.name,
                        "installments": req.body.installments,
                        "payment_method_id": req.body.method,
                        "payer": {
                            "email": req.app.locals.oauth.token.user.email,
                            "id": user.mp.id
                        },
                        "issuer_id": req.body.issuer.toString(),
                        "application_fee": fee,
                        "notification_url": "https://api.shopear.com/mp/callback"
                    }

                    mercadopago.payment.create(payload, {}, function (err, payment) {
```

pero asi y todo me tira el error

MercadoPagoError: You cannot use application_fee with this payment

cual puede ser mi problema???

**Comment by arielfr** [comment]
Buenas, te creaste un Marketplace?

Igualmente con cambiar las configuraciones on the fly, te diria que tengas cuidado. Al hacer un `require` en NodeJS, el objeto es un singleton. Por ende, si estas procesando 2 pagos al mismo tiempo con 2 configuraciones de MercadoPago distintas, vas a tener race condition.

**Comment by paulogdm** [comment]
This is worse than I thought:
If you know the basics of Node you know that a "require" is always a single instance of a module.
When using MP Connect or the MP Applications, it instructs you to do the following:
```
var mercadopago = require('mercadopago');
mercadopago.configurations.setAccessToken(config.access_token);

var payment_data = {
  transaction_amount: 100,
  token: 'ff8080814c11e237014c1ff593b57b4d'
  description: 'Title of what you are paying for',
  installments: 1,
  payment_method_id: 'visa',
  user_token: "ENV_USER_TOKEN"
  payer: {
    email: 'test_user_3931694@testuser.com'
  }
};

mercadopago.payment.create(payment_data).then(function (data) {
  // Do Stuff...
}).catch(function (error) {
  // Do Stuff...
});
``` 
Of course the example above with `new` is deprecated. But the following lines can confirm that MP Connect is not supported by the SDK at all, **when using it with mercadopago.configure()**:
https://github.com/mercadopago/dx-nodejs/blob/a4ea817e1e348577f42a49d1457de0fd40b4d67e/lib/configurations.js#L5
https://github.com/mercadopago/dx-nodejs/blob/a4ea817e1e348577f42a49d1457de0fd40b4d67e/lib/configurations.js#L78

What is the official way of doing this, since the documentation is outdated and the examples nonexistent for MPConnect?
